CREATE OR REPLACE PROCEDURE GET_BILL_NO
(
  P_BILL_NO_NAME  BILL_NO_CREATE.BILL_NO_NAME%TYPE,
  P_BILL_NO_VALUE OUT VARCHAR2
)
IS
  V_CUR_MONTH BILL_NO_CREATE.CUR_MONTH%TYPE;
BEGIN
  V_CUR_MONTH := TO_CHAR(SYSDATE, 'YYMMDD');

  IF P_BILL_NO_NAME='INS'
THEN
  UPDATE BILL_NO_CREATE A
     SET A.CUR_BILL_INDEX = LPAD(DECODE(A.CUR_MONTH, V_CUR_MONTH, TO_NUMBER(A.CUR_BILL_INDEX) + 1, 1), LENGTH(A.CUR_BILL_INDEX), '0'),
         A.CUR_MONTH      = V_CUR_MONTH
   WHERE A.BILL_NO_NAME = P_BILL_NO_NAME
  RETURNING  A.CUR_BILL_INDEX INTO P_BILL_NO_VALUE;
ELSE
  UPDATE BILL_NO_CREATE A
     SET A.CUR_BILL_INDEX = LPAD(DECODE(A.CUR_MONTH, V_CUR_MONTH, TO_NUMBER(A.CUR_BILL_INDEX) + 1, 1), LENGTH(A.CUR_BILL_INDEX), '0'),
         A.CUR_MONTH      = V_CUR_MONTH
   WHERE A.BILL_NO_NAME = P_BILL_NO_NAME
  RETURNING A.BILL_QZ || A.CUR_MONTH || A.CUR_BILL_INDEX INTO P_BILL_NO_VALUE;
END IF;

END;